version: '3.8'
services:
  app:
    build: .
    ports:
      - "5555:5555"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tms
      POSTGRES_PASSWORD: tms
      POSTGRES_DB: tms_db
    ports:
      - "5432:5432"